// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from GameProtocol.proto

package com.aspectgaming.net.game.data;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

public final class MathParam implements Externalizable, Message<MathParam>, Schema<MathParam> {

    public static Schema<MathParam> getSchema() {
        return DEFAULT_INSTANCE;
    }

    public static MathParam getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    static final MathParam DEFAULT_INSTANCE = new MathParam();

    public String Key;
    public String Value;

    public MathParam() {}

    @Override
    public String toString() {
        return "MathParam{" +
                    "key=" + Key +
                    ", value=" + Value +
                '}';
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<MathParam> cachedSchema() {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public MathParam newMessage() {
        return new MathParam();
    }

    public Class<MathParam> typeClass() {
        return MathParam.class;
    }

    public String messageName() {
        return MathParam.class.getSimpleName();
    }

    public String messageFullName() {
        return MathParam.class.getName();
    }

    public boolean isInitialized(MathParam message) {
        return true;
    }

    public void mergeFrom(Input input, MathParam message) throws IOException {
        for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this)) {
            switch (number) {
            case 0:
                return;
            case 1:
                message.Key = input.readString();
                break;
            case 2:
                message.Value = input.readString();
                break;
            default:
                input.handleUnknownField(number, this);
            }
        }
    }

    public void writeTo(Output output, MathParam message) throws IOException {
        if (message.Key != null) output.writeString(1, message.Key, false);

        if (message.Value != null) output.writeString(2, message.Value, false);
    }

    public String getFieldName(int number) {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name) {
        return Integer.parseInt(name);
    }

}
