// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from GameProtocol.proto

package com.aspectgaming.net.game.data;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.aspectgaming.net.ProtoUtil;

public final class ProgressiveValuesData implements Externalizable, Message<ProgressiveValuesData>, Schema<ProgressiveValuesData> {

    public static Schema<ProgressiveValuesData> getSchema() {
        return DEFAULT_INSTANCE;
    }

    public static ProgressiveValuesData getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    static final ProgressiveValuesData DEFAULT_INSTANCE = new ProgressiveValuesData();

    public long[] Values;

    public ProgressiveValuesData() {}

    @Override
    public String toString() {
        return "ProgressiveValuesData{" +
                    "values=" + Values +
                '}';
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ProgressiveValuesData> cachedSchema() {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public ProgressiveValuesData newMessage() {
        return new ProgressiveValuesData();
    }

    public Class<ProgressiveValuesData> typeClass() {
        return ProgressiveValuesData.class;
    }

    public String messageName() {
        return ProgressiveValuesData.class.getSimpleName();
    }

    public String messageFullName() {
        return ProgressiveValuesData.class.getName();
    }

    public boolean isInitialized(ProgressiveValuesData message) {
        return true;
    }

    public void mergeFrom(Input input, ProgressiveValuesData message) throws IOException {
        List<Long> Values = null;
        try {
            for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this)) {
                switch (number) {
                case 0:
                    return;
                case 1:
                    if (Values == null) Values = new ArrayList<Long>();
                    Values.add(input.readInt64());
                    break;
                default:
                    input.handleUnknownField(number, this);
                }
            }
        } finally {
            message.Values = ProtoUtil.toLongArray(Values);
        }
    }

    public void writeTo(Output output, ProgressiveValuesData message) throws IOException {
        if (message.Values != null) {
            for (Long values : message.Values) {
                if (values != null) output.writeInt64(1, values, true);
            }
        }
    }

    public String getFieldName(int number) {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name) {
        return Integer.parseInt(name);
    }

}
