// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from GameProtocol.proto

package com.aspectgaming.net.game.data;

public enum ProtocolTypes implements io.protostuff.EnumLite<ProtocolTypes> {
    HEART_BEAT(30532),
    COMMAND(30533),
    RESET_S2C(31000),
    SETTING_S2C(31001),
    CONTEXT_S2C(31002),
    GAME_RECALL_S2C(31003),
    PROGRESSIVE_S2C(31004),
    PAYTABLE_S2C(31005),
    REGISTER_C2S(31500);

    public final int number;

    private ProtocolTypes(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public static ProtocolTypes valueOf(int number) {
        switch (number) {
            case 30532: return HEART_BEAT;
            case 30533: return COMMAND;
            case 31000: return RESET_S2C;
            case 31001: return SETTING_S2C;
            case 31002: return CONTEXT_S2C;
            case 31003: return GAME_RECALL_S2C;
            case 31004: return PROGRESSIVE_S2C;
            case 31005: return PAYTABLE_S2C;
            case 31500: return REGISTER_C2S;
            default: return null;
        }
    }
}
