// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from OneWallProtocol.proto

package com.aspectgaming.media.onewall.data;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

@Generated("java_bean")
public final class LedInfo implements Externalizable, Message<LedInfo>, Schema<LedInfo>
{

    public static Schema<LedInfo> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static LedInfo getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final LedInfo DEFAULT_INSTANCE = new LedInfo();

    
    private long startTime;
    private long machineOffsetTime;
    private long duration;
    private String script;
    private String mask;

    public LedInfo()
    {

    }

    @Override
    public String toString() {
        return "LedInfo{" +
                    "startTime=" + startTime +
                    ", machineOffsetTime=" + machineOffsetTime +
                    ", duration=" + duration +
                    ", script=" + script +
                    ", mask=" + mask +
                '}';
    }
    // getters and setters

    // startTime

    public long getStartTime()
    {
        return startTime;
    }


    public void setStartTime(long startTime)
    {
        this.startTime = startTime;
    }

    // machineOffsetTime

    public long getMachineOffsetTime()
    {
        return machineOffsetTime;
    }


    public void setMachineOffsetTime(long machineOffsetTime)
    {
        this.machineOffsetTime = machineOffsetTime;
    }

    // duration

    public long getDuration()
    {
        return duration;
    }


    public void setDuration(long duration)
    {
        this.duration = duration;
    }

    // script

    public String getScript()
    {
        return script;
    }


    public void setScript(String script)
    {
        this.script = script;
    }

    // mask

    public String getMask()
    {
        return mask;
    }


    public void setMask(String mask)
    {
        this.mask = mask;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<LedInfo> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public LedInfo newMessage()
    {
        return new LedInfo();
    }

    public Class<LedInfo> typeClass()
    {
        return LedInfo.class;
    }

    public String messageName()
    {
        return LedInfo.class.getSimpleName();
    }

    public String messageFullName()
    {
        return LedInfo.class.getName();
    }

    public boolean isInitialized(LedInfo message)
    {
        return true;
    }

    public void mergeFrom(Input input, LedInfo message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.startTime = input.readInt64();
                    break;
                case 2:
                    message.machineOffsetTime = input.readInt64();
                    break;
                case 3:
                    message.duration = input.readInt64();
                    break;
                case 4:
                    message.script = input.readString();
                    break;
                case 5:
                    message.mask = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, LedInfo message) throws IOException
    {
        if(message.startTime != 0)
            output.writeInt64(1, message.startTime, false);

        if(message.machineOffsetTime != 0)
            output.writeInt64(2, message.machineOffsetTime, false);

        if(message.duration != 0)
            output.writeInt64(3, message.duration, false);

        if(message.script != null)
            output.writeString(4, message.script, false);

        if(message.mask != null)
            output.writeString(5, message.mask, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
