// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from OneWallProtocol.proto

package com.aspectgaming.media.onewall.data;

import javax.annotation.Generated;

@Generated("java_bean")
public enum ProtocolTypes implements io.protostuff.EnumLite<ProtocolTypes>
{
    HEART_BEAT(30532),
    REPORT_C2S(30535),
    SETTING_S2C(31000),
    MEDIA_S2C(31001);
    
    public final int number;
    
    private ProtocolTypes (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static ProtocolTypes valueOf(int number)
    {
        switch(number) 
        {
            case 30532: return HEART_BEAT;
            case 30535: return REPORT_C2S;
            case 31000: return SETTING_S2C;
            case 31001: return MEDIA_S2C;
            default: return null;
        }
    }
}
